{
  description = "burnrate — month-to-date LLM spend and projected burn, for a status bar";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f:
        nixpkgs.lib.genAttrs systems (system: f system nixpkgs.legacyPackages.${system});
    in
    {
      packages = forAllSystems (_: pkgs: rec {
        # The completion scripts ship with the package, generated by running the
        # freshly-built binary rather than checked in, so they cannot drift from
        # the real parser. Each lands in the standard location its shell reads:
        #   bash -> share/bash-completion/completions/burnrate
        #   zsh  -> share/zsh/site-functions/_burnrate
        #   fish -> share/fish/vendor_completions.d/burnrate.fish
        burnrate = (pkgs.haskellPackages.callCabal2nix "burnrate" ./. {
        }).overrideAttrs (old: {
          # The completion scripts ship with the package, generated by running
          # the freshly-built binary rather than checked in, so they cannot drift
          # from the real parser.
          postInstall = (old.postInstall or "") + ''
            mkdir -p $out/share/bash-completion/completions
            mkdir -p $out/share/zsh/site-functions
            mkdir -p $out/share/fish/vendor_completions.d
            $out/bin/burnrate --bash-completion-script burnrate > $out/share/bash-completion/completions/burnrate
            $out/bin/burnrate --zsh-completion-script  burnrate > $out/share/zsh/site-functions/_burnrate
            $out/bin/burnrate --fish-completion-script burnrate > $out/share/fish/vendor_completions.d/burnrate.fish
          '';
        });
        default = burnrate;
      });

      apps = forAllSystems (system: _pkgs: {
        burnrate = {
          type = "app";
          program = "${self.packages.${system}.burnrate}/bin/burnrate";
          meta = {
            mainProgram = "burnrate";
            description = "Install & run burnrate — LLM spend & projected burn, for a status bar.";
          };
        };
        default = self.apps.${system}.burnrate;
      });

      devShells = forAllSystems (system: pkgs: {
        default = pkgs.haskellPackages.shellFor {
          packages = _: [ self.packages.${system}.burnrate ];
          withHoogle = false;
          nativeBuildInputs = with pkgs.haskellPackages; [
            cabal-install
            haskell-language-server
            hlint
            ormolu
          ];
          # `pass` is how keys are resolved by default; keep it on PATH so the
          # dev shell can run the thing for real.
          buildInputs = [ pkgs.pass pkgs.bash-completion pkgs.zsh-completions pkgs.fish ];
        };
      });

      checks = forAllSystems (system: _pkgs: {
        inherit (self.packages.${system}) burnrate;
      });
    };
}
